######################## default configuration ####################
baseURL = "http://larylarylarylarylarylarylarylarylarylarylarylarylarylarylary.com"
languageCode = "en-us"
title = "larylarylarylarylarylarylarylarylarylarylarylarylarylarylary"
theme = "lary-lary"
summaryLength = "10"


############################## Output ###############################
[outputs]
home = ["HTML", "RSS"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################## Output ###############################
# JS Plugins
[[params.plugins.js]]
URL = "plugins/plugins.js"


############################## navigation ###########################
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
  weight = 2
  name = "Services"
  hasChildren = true

    [[menu.main]]
    parent = "Services"
    name = "Content Creation"
    URL = "content/"
    weight = 1
    
    [[menu.main]]
    parent = "Services"
    name = "Bartending Services"
    URL = "bartending/"
    weight = 2


[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3




#################### default parameters ##############################
[params]
logo = "images/bb-images/logos/horizontal/svg/Light.svg"
home = "Home"
# Meta data
description = "This is meta description"
author = "TheBaerBønes"
# contact form action
contact_form_action = "https://formspree.io/f/xnnqzzpp" # contact form works with https://formspree.io
# footer content
footer_content = ""

# google map
[params.map]
enable = true
gmap_api = ""
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
name = "instagram"
icon = "fa-instagram"
link = "https://www.instagram.com/bourbon_and_bokeh"

[[params.social]]
name = ""
icon = "" # fontawesome icon pack v4.7
link = ""

[[params.social]]
name = ""
icon = "" # fontawesome icon pack v4.7
link = ""
